version: "3.9"

services:
  ml_flask:
    build:
      context: "../../ML_FLASK_APP"
      dockerfile: "docker/Dockerfile"
    volumes:
      - ../../ML_FLAK_APP:/app
    stdin_open: true
    tty: true
    ports:
      - "5000:5000"
    image: ml_flask:app
    container_name: ml_container
